import Link from 'next/link'

export default function TermsPage() {
  return (
    <main style={{ backgroundColor: 'var(--brand-bg)', minHeight: '100vh', color: 'var(--brand-text)', padding: '4rem 1.5rem' }}>
      <div style={{ maxWidth: '680px', margin: '0 auto' }}>
        <Link href="/" style={{ color: '#2563eb', textDecoration: 'none', fontSize: '0.88rem', display: 'inline-block', marginBottom: '2.5rem' }}>
          ← Back
        </Link>

        <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '0.5rem', letterSpacing: '-0.02em' }}>Terms of Use</h1>
        <p style={{ fontSize: '0.85rem', color: 'var(--brand-text-subtle)', marginBottom: '2.5rem' }}>Last updated: March 2026</p>

        {[
          {
            title: 'The service',
            body: 'MyTwenties provides a personality and direction assessment for people aged 18–30. The report generated is for personal insight and educational purposes. It is not a substitute for professional psychological, financial, or career advice.'
          },
          {
            title: 'Eligibility',
            body: 'You must be 18 years of age or older to use MyTwenties. By using the service, you confirm that you meet this requirement.'
          },
          {
            title: 'Accuracy',
            body: 'Your report is generated by AI based on your responses. While we aim to make the output as accurate and useful as possible, we cannot guarantee that all insights will apply to your specific situation. Use your own judgement.'
          },
          {
            title: 'Payments',
            body: 'The base report is free. The full paid report ($29) is a one-time purchase. If you are not satisfied with your paid report, you can request a full refund within 30 days by emailing sam@mytwenties.com.'
          },
          {
            title: 'Prohibited use',
            body: 'You may not reproduce, resell, or redistribute any part of your report without permission. You may not attempt to reverse-engineer the assessment or report generation system.'
          },
          {
            title: 'Limitation of liability',
            body: 'MyTwenties is not liable for any decisions made based on your report. The report is a tool for self-reflection, not professional advice.'
          },
          {
            title: 'Contact',
            body: 'For any questions about these terms, email sam@mytwenties.com.'
          }
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--brand-text)' }}>{title}</h2>
            <p style={{ fontSize: '0.95rem', lineHeight: 1.8, color: 'var(--brand-text-muted)', margin: 0 }}>{body}</p>
          </div>
        ))}
      </div>
    </main>
  )
}
